sudo: required
services:
  - docker

before_install:
  - chmod 0777 ./node_modules/.bin/mocha
  - docker build -t mohsinkarim/wab-docker -f Dockerfile.dev .

script: 
  - docker run mohsinkarim/wab-docker npm run test

after_success:
  - docker build -t mohsinkarim/wab-image .
 
  - echo "$pd" | docker login -u "$user" --password-stdin

  - docker push mohsinkarim/wab-image
 
deploy:
  - provider: elasticbeanstalk
    region: "us-east-1"
    app: "wab-docker-prod"
    env: "WabDockerProd-env"
    bucket_name: "elasticbeanstalk-us-east-1-778904096101"
    bucket_path: "wab-docker-prod"
    on:
      branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
      secure: "$Secret"
  - provider: elasticbeanstalk
    region: "us-east-1"
    app: "wab-docker-prod"
    env: "WabDockerTest"
    bucket_name: "elasticbeanstalk-us-east-1-778904096101"
    bucket_path: "WabDockerTest"
    on:
      branch: testing
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
      secure: "$Secret"
  - provider: elasticbeanstalk
    region: "us-east-1"
    app: "wab-docker-prod"
    env: "WabDockerDevelopment "
    bucket_name: "elasticbeanstalk-us-east-1-778904096101"
    bucket_path: "WabDockerDevelopment"
    on:
      branch: development
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
      secure: "$Secret"